### ISSUE TITLE
Won't work ;-(

### ISSUE THREAD

**Issue by wurstel** [AlexDisler/ionic-lock-screen#2]
Hi, I followed the install instructions, but only getting this error now:

Uncaught Error: [$injector:modulerr] Failed to instantiate module starter due to:
Error: [$injector:modulerr] Failed to instantiate module ionic-lock-screen due to:
Error: [$injector:nomod] Module 'ionic-lock-screen' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.

Am I doing something wong? Thank you!

**Comment by iwok** [comment]
i copied it to `/www/lib` and added `<script src="lib/ionic-lock-screen/dist/index.js"></script>` to index.html
worked for me

**Comment by barkoczi** [comment]
Gulp does not inject your package automatically. Add to package's bower.json the following code: 
```
  "main": [
    "./dist/index.js"
  ],
```
