### ISSUE TITLE
how to adjust the width and height of the lock

### ISSUE THREAD

**Issue by vevHack** [AlexDisler/ionic-lock-screen#3]
my demo's height can not auto scale

**Comment by vevHack** [comment]
![image](https://cloud.githubusercontent.com/assets/10921445/13378974/3ddfa498-de53-11e5-9265-e86d1d077f4d.png)

**Comment by barkoczi** [comment]
As it written in readme, insert the <lock-screen></lock-screen> direct after <body> tag.
