### ISSUE TITLE
Add ability to create a passcode?

### ISSUE THREAD

**Issue by kylefox** [AlexDisler/ionic-lock-screen#4]
This library works awesome, nice work :+1: 

Is there a way to use this screen to allow the user to _create_ their initial passcode? From what I could tell `$lockScreen.show(params)` must be initialized with the correct code. So I'm wondering how you could use this library to let the user set the code in the first place.

I need this functionality myself, so if the library _can't_ do it currently I'll fork and submit a PR once it's done :+1:

**Comment by AlexDisler** [comment]
Thanks! There's no way to do it currently. I also need this functionality so I was planning to do it but never got around to it. If you can open a pull request that would be awesome.

**Comment by kylefox** [comment]
Turns out I actually don't require lock screen functionality any longer, so I likely won't get to this :cry:
