### ISSUE TITLE
Delete wrong input?

### ISSUE THREAD

**Issue by CarsonChen1129** [AlexDisler/ionic-lock-screen#6]
Hi, thank you very much for making this amazing plugin. I wonder is there a way to add a "delete" button or delete the wrong number that I just pressed? Do I have to finish entering the four digit codes if I find out I pressed the wrong number at the first place? I would appreciate for any reply. Thank you very much.

**Comment by AlexDisler** [comment]
Hi, there's no support for it at the moment but it can be useful as an optional functionality.

**Comment by CarsonChen1129** [comment]
Thank you very much for your reply, I added those buttons for this plugin and made a pull request. Hope you like it. :)

**Comment by AlexDisler** [comment]
thanks
